spring.application.name=KoKo
server.port=1620

# PostgreSQL connection
spring.datasource.url=JDBC:postgresql://localhost:5432/koko_db
spring.datasource.username=postgres
spring.datasource.password=M@lebogeng98
spring.datasource.driver-class-name=org.postgresql.Driver

# JPA / Hibernate
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
