spring.application.name=profile
# Tell Spring to use the H2 database
spring.datasource.url=jdbc:h2:mem:contactMedb
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=password

# Tell Spring to automatically build our tables for us
spring.jpa.database-platform=org.hibernate.dialect.H2Dialect
spring.jpa.hibernate.ddl-auto=update

# Turn on the database web viewer so we can look inside the vault
spring.h2.console.enabled=true
spring.h2.console.path=/h2-console