spring.application.name=profile
# 1. The exact address of your new Postgres database
spring.datasource.url=jdbc:postgresql://localhost:5432/contactmedb
# 2. The credentials we just created in the terminal
spring.datasource.username=lebo
spring.datasource.password=password1111
# 3. Tell Spring Boot to use the Postgres dialect (language)
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
# 4. Automatically build our tables (just like before)
spring.jpa.hibernate.ddl-auto=update